Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [13]:
from sklearn import datasets
import numpy as np

In [14]:
iris = datasets.load_iris()

In [15]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [16]:
#task 1
data = np.array(iris.data)
feature_names = np.array(iris.feature_names)
feature_names

array(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'], dtype='<U17')

In [17]:
data.shape

(150, 4)

In [18]:
for i in range(4):

    print(f"The mean,std. dev and variance for feature_{i+1}")
    print("Mean: ", np.mean(data[:,i]))
    print("Std. Dev:", np.std(data[:,i]))
    print("Variance: ", np.var(data[:,i]))
    print("###########################################################################")

The mean,std. dev and variance for feature_1
Mean:  5.843333333333334
Std. Dev: 0.8253012917851409
Variance:  0.6811222222222223
###########################################################################
The mean,std. dev and variance for feature_2
Mean:  3.0573333333333337
Std. Dev: 0.4344109677354946
Variance:  0.1887128888888889
###########################################################################
The mean,std. dev and variance for feature_3
Mean:  3.7580000000000005
Std. Dev: 1.759404065775303
Variance:  3.0955026666666665
###########################################################################
The mean,std. dev and variance for feature_4
Mean:  1.1993333333333336
Std. Dev: 0.7596926279021594
Variance:  0.5771328888888888
###########################################################################

In [19]:
import pandas as pd  

df = pd.DataFrame(data,columns=feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [20]:
samples= df.iloc[:100, 2:]

samples_gt_mean = samples['petal length (cm)'] > np.mean(samples['petal length (cm)'])
samples_gt_mean.sum()

50

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [21]:
columns = list(samples.columns)

samples_scaled = samples.copy(deep = True)

for col in columns:
    print(f"Mean of {col} : ", samples[col].mean())
    print(f"std dev of {col} : ", samples[col].std())

for col in columns:
    samples_scaled[col] = (samples[col] - samples[col].mean())/samples[col].std()

print(samples_scaled)

Mean of petal length (cm) :  2.861
std dev of petal length (cm) :  1.4495485190537465
Mean of petal width (cm) :  0.7859999999999998
std dev of petal width (cm) :  0.5651530587354014
    petal length (cm)  petal width (cm)
0           -1.007900         -1.036887
1           -1.007900         -1.036887
2           -1.076887         -1.036887
3           -0.938913         -1.036887
4           -1.007900         -1.036887
..                ...               ...
95           0.923736          0.732545
96           0.923736          0.909488
97           0.992723          0.909488
98           0.095892          0.555602
99           0.854749          0.909488

[100 rows x 2 columns]

Std. Dev is 1 and Mean is 0 means the data is normally distributed. We donot need to scale the data.

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [22]:
import seaborn as sns 

data = sns.load_dataset('titanic')

In [23]:
data.head()
data.tail()
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [24]:
#null values by column
for col in data.columns:
    print(f"Null values in {col} : ", data[col].isnull().sum())

Null values in survived :  0
Null values in pclass :  0
Null values in sex :  0
Null values in age :  177
Null values in sibsp :  0
Null values in parch :  0
Null values in fare :  0
Null values in embarked :  2
Null values in class :  0
Null values in who :  0
Null values in adult_male :  0
Null values in deck :  688
Null values in embark_town :  2
Null values in alive :  0
Null values in alone :  0

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [25]:
female_passenger_in_first_class =  data[(data['sex'] == 'female') & (data['class'] == 'First')]
# survival rate of 1st class female passengers
survival_rate = (sum(female_passenger_in_first_class['survived']) * 100) / len(female_passenger_in_first_class)
survival_rate

96.80851063829788

In [26]:
# overall survival rate 
ovr_survival_rate = (sum(data.survived) * 100)/ len(data)
ovr_survival_rate

38.38383838383838

On comparing the survival rates we can conclude that female passengers in 1st class were given the first preference in the rescue as compared to other passengers.

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [27]:
mean_of_age = data['age'].mean()
data['age'].fillna(mean_of_age, inplace=True)

mode_of_embarked = data['embarked'].mode()
data['embarked'].fillna(mode_of_embarked, inplace=True)

data.drop(columns='deck', inplace= True)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\3848297631.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['age'].fillna(mean_of_age, inplace=True)
C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\3848297631.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['embarked'].fillna(mode_of_embarked, inplace=True)

Diff. stratergies are used for different columns based on it data type, distribution etc.

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [28]:
data['family_size'] = data['sibsp'] + data['parch'] + 1
data['is_alone'] = np.where(data['sibsp'] + data['parch'] == 0, 1, 0)

data.groupby('is_alone')['survived'].mean()

is_alone
0    0.505650
1    0.303538
Name: survived, dtype: float64

adding well engineered features like family size and is_alone can provide additional insights into the survival rates of passengers. For instance, passengers who were alone might have had different survival chances compared to those with family members on board. By analyzing the survival rates based on these new features, we can gain a deeper understanding of the factors that influenced survival during the Titanic disaster.

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [29]:
tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [35]:
# tip percentage
tips['tip_percentage'] = tips['tip']/tips['total_bill']

tip_by_day = tips.groupby('day').agg({'tip' : 'sum'})
tip_by_day

C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\1925498548.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tip_by_day = tips.groupby('day').agg({'tip' : 'sum'})

         tip
day
Thur  171.83
Fri    51.96
Sat   260.40
Sun   247.39

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [40]:
tips_filtered = tips[(tips.total_bill > 20) & (tips.tip < 3)]
avg_tips_by_gender =  tips_filtered.groupby('sex')['tip'].mean()
avg_tips_by_smoker =  tips_filtered.groupby('smoker')['tip'].mean()
avg_tip_by_gender_smoker = tips_filtered.groupby(['sex', 'smoker'])['tip'].mean()

avg_tips_by_gender,avg_tips_by_smoker,avg_tip_by_gender_smoker

C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\1830257919.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_tips_by_gender =  tips_filtered.groupby('sex')['tip'].mean()
C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\1830257919.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_tips_by_smoker =  tips_filtered.groupby('smoker')['tip'].mean()
C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\1830257919.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_tip_by_gender_smoker = tips_filtered.groupby(['sex', 'smoker'])['tip'].mean()

(sex
 Male      2.060769
 Female    2.478750
 Name: tip, dtype: float64,
 smoker
 Yes    2.114000
 No     2.316364
 Name: tip, dtype: float64,
 sex     smoker
 Male    Yes       1.965714
         No        2.171667
 Female  Yes       2.460000
         No        2.490000
 Name: tip, dtype: float64)

male smokers are tipping low.

Filtering the data on the basis of business rules can help us in eliminating situations where the model doesnot predict or generalize irrelevant trends. Like for example the model shouldnot predict a negative value as tip. A tip should always be positive.

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [42]:
arr_1 = np.random.rand(3,2)
arr_2 = np.random.rand(3,2)

vertical_stack = np.vstack((arr_1,arr_2))
horizontal_stack = np.hstack((arr_1, arr_2))

vertical_stack.reshape(2,6)

vertical_stack,horizontal_stack

(array([[0.43719459, 0.89021342],
        [0.61715397, 0.81328281],
        [0.49828436, 0.77377888],
        [0.33913774, 0.18113264],
        [0.96263942, 0.04263914],
        [0.7385597 , 0.46103029]]),
 array([[0.43719459, 0.89021342, 0.33913774, 0.18113264],
        [0.61715397, 0.81328281, 0.96263942, 0.04263914],
        [0.49828436, 0.77377888, 0.7385597 , 0.46103029]]))

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [44]:
df = sns.load_dataset('titanic')

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [46]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [47]:
#handling missing values
df.drop(columns = 'deck', axis= 1, inplace=True)
df['age'].fillna(df['age'].mean(),inplace= True)
df['embarked'].fillna(df['embarked'].mode(), inplace= True)

#handle encoding 
df['sex'] = df['sex'].map({'male' : 0, 'female' : 1})
df['embarked'] = df['embarked'].map({'C':0, 'Q': 1, 'S': 2})

# normalize columns 
for col in ['age', 'fare']:
    df[col] = (df[col] - df[col].mean())/df[col].std()

df_np = df.values 
df_np

C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\2726527672.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace= True)
C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\2726527672.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['embarked'].fillna(df['embarked'].mode(), inplace= True)

array([[0, 3, 0, ..., 'Southampton', 'no', False],
       [1, 1, 1, ..., 'Cherbourg', 'yes', False],
       [1, 3, 1, ..., 'Southampton', 'yes', True],
       ...,
       [0, 3, 1, ..., 'Southampton', 'no', False],
       [1, 1, 0, ..., 'Cherbourg', 'yes', True],
       [0, 3, 0, ..., 'Queenstown', 'no', True]], dtype=object)

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [50]:
iris_data = np.array(iris.data)
iris_df = pd.DataFrame(iris_data, columns= iris.feature_names)
iris_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [51]:
iris_df.corr()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
sepal length (cm),1.000000,-0.117570,0.871754,0.817941
sepal width (cm),-0.117570,1.000000,-0.428440,-0.366126
petal length (cm),0.871754,-0.428440,1.000000,0.962865
petal width (cm),0.817941,-0.366126,0.962865,1.000000

high correlation between petal length, petal width and sepal length

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [53]:
titanic = sns.load_dataset('titanic')

In [54]:
titanic['age_group'] = titanic['age'].apply(lambda x: 'child' if x < 18 else 'adult' if x < 60 else 'senior')

In [56]:
survival_rate_by_age_group = titanic.groupby('age_group')['survived'].mean()
survival_rate_by_age_group

age_group
adult     0.386087
child     0.539823
senior    0.290640
Name: survived, dtype: float64

Incase of rescue operations women and children are given priority. Hence, the survival rate of children is higher

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [58]:
error_values = np.random.rand(1000)
print(error_values.mean())
print(error_values.std())
outliers = error_values[(error_values < (error_values.mean() - 2*error_values.std())) | (error_values > (error_values.mean() + 2*error_values.std()))]
outliers

0.48430643783503546
0.28076417949431903

array([], dtype=float64)

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [59]:
tips

     total_bill   tip     sex smoker   day    time  size  tip_percentage
0         16.99  1.01  Female     No   Sun  Dinner     2        0.059447
1         10.34  1.66    Male     No   Sun  Dinner     3        0.160542
2         21.01  3.50    Male     No   Sun  Dinner     3        0.166587
3         23.68  3.31    Male     No   Sun  Dinner     2        0.139780
4         24.59  3.61  Female     No   Sun  Dinner     4        0.146808
..          ...   ...     ...    ...   ...     ...   ...             ...
239       29.03  5.92    Male     No   Sat  Dinner     3        0.203927
240       27.18  2.00  Female    Yes   Sat  Dinner     2        0.073584
241       22.67  2.00    Male    Yes   Sat  Dinner     2        0.088222
242       17.82  1.75    Male     No   Sat  Dinner     2        0.098204
243       18.78  3.00  Female     No  Thur  Dinner     2        0.159744

[244 rows x 8 columns]

In [62]:
tip_perc_by_day_time = tips.groupby(['day', 'time'])['total_bill'].sum()
tip_perc_by_day_time

C:\Users\rkbeh\AppData\Local\Temp\ipykernel_43656\3026346253.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tip_perc_by_day_time = tips.groupby(['day', 'time'])['total_bill'].sum()

day   time
Thur  Lunch     1077.55
      Dinner      18.78
Fri   Lunch       89.92
      Dinner     235.96
Sat   Lunch        0.00
      Dinner    1778.40
Sun   Lunch        0.00
      Dinner    1627.16
Name: total_bill, dtype: float64

Sat Dinner has the highest revenue